Repository FRONTENDSCHOOL5/final-01-focal, pull requests merged in 2023-08, with the labels that each got.

#85 [API] 상품 api 분리
  src/api/apis/product.js
  src/components/Profile/ProfileProducts.jsx
  src/pages/ProductEditPage.jsx
  src/pages/ProductUploadPage.jsx
  src/pages/SignUpPage.jsx
Labels: ♻️ 리팩토링

#87 [Follow] 팔로우 페이지 구조변경
  src/components/Follow/FollowNone.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: ♻️ 리팩토링

#88 [Post] 이미지 슬라이드 애니메이션, aria-label 추가
  src/components/Common/PostCard/PostCard.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#86 [Profile] 프로필 게시글 구조 변경
  src/components/Profile/PostAlignButtons.jsx
  src/components/Profile/PostNone.jsx
  src/components/Profile/ProfilePosts.jsx
Labels: ♻️ 리팩토링

#89 [Chat] input 리렌더링 방지, 전송기능 추가
  src/components/Chat/ChatRoom.jsx
  src/components/Common/Input/TextInputBox.jsx
  src/pages/ChatRoomPage.jsx
Labels: ✨ 기능 추가

#92 [ETC] Splash 화면 로직 변경
  src/App.js
  src/layouts/Splash/Splash.jsx
  src/pages/SplashPage.jsx
  src/routes/PrivateRoute.jsx
  src/routes/Router.jsx
Labels: ♻️ 리팩토링

#93 [Common] Navbar 색상 변경 오류수정
  src/layouts/NavBar/NavBar.jsx
  src/layouts/NavBar/NavBarItem.jsx
Labels: 🐛 버그

#95 [Search] SearchPage 리팩토링
  src/assets/images/basic-profile-m.png
  src/assets/images/basic-profile-s.png
  src/components/Chat/ChatRoom.jsx
  src/components/Common/Input/ProfileImageUploader.jsx
  src/components/Common/Input/TextInputBox.jsx
  src/components/Common/PostCard/PostCard.jsx
  src/components/Common/UserInfo/UserInfo.jsx
  src/components/Post/PostComment.jsx
  src/components/Post/PostUpload.jsx
  src/components/Profile/ProfileInfo.jsx
  src/pages/SearchPage.jsx
  src/routes/Router.jsx
  src/utils/getProperImgSrc.js
  src/utils/handleImageError.js
Labels: ✨ 기능 추가, 💄 HTML/CSS, ♻️ 리팩토링

#96 [Common] Form 관련 컴포넌트 Refactoring
  src/components/Common/Button/Button.jsx
  src/components/Common/ProfileForm/ProfileForm.jsx
  src/components/Post/PostUpload.jsx
  src/constants/alertMessage.js
  src/hooks/useHandleResizeHeight.js
  src/hooks/useModal.js
  src/layouts/Header/Header.jsx
  src/pages/PostEditPage.jsx
  src/pages/PostUploadPage.jsx
  src/pages/ProductUploadPage.jsx
  src/pages/ProfileEditPage.jsx
  src/pages/SignUpPage.jsx
Labels: 🐛 버그, ♻️ 리팩토링

#97 [Feed] 무한 스크롤 기능 구현
  src/api/apis/post.js
  src/components/Post/PostsFeed.jsx
  src/pages/HomePage.jsx
Labels: ✨ 기능 추가, ♻️ 리팩토링

#100 [Chat] 채팅리스트 목록수정
  src/components/Chat/ChatList.jsx
  src/pages/ChatListPage.jsx
  src/utils/getDate.js
Labels: ✨ 기능 추가, ♻️ 리팩토링

#98 [Follow] follow 페이지 무한스크롤 구현
  src/api/apis/follow.js
  src/hooks/useScrollBottom.js
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: ✨ 기능 추가

#99 [Profile] 프로필 페이지의 게시글 무한스크롤 구현
  src/api/apis/post.js
  src/components/Profile/ProfilePosts.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: ✨ 기능 추가
