Repository FRONTENDSCHOOL5/final-01-focal, pull requests merged in 2023-06, with the labels that each got.

#1 [Common] 기본 버튼 UI 구현
  src/components/Button/Button.jsx
Labels: HTML/CSS

#2 [Login] LoginPage UI 구현
  src/components/Header/TitleHeader.jsx
  src/components/Input/TextInput.jsx
  src/components/Login/LoginForm.jsx
  src/pages/LoginPage.jsx
Labels: HTML/CSS

#3 [SignUp] SignUp페이지 UI 구현
  src/assets/images/basic-profile-s.png
  src/assets/images/basic-profile.png
  src/assets/images/image-upload.png
  src/assets/images/profile-upload.png
  src/components/Button/Button.jsx
  src/components/ProfileInputContainer/ProfileImageUploader.jsx
  src/components/ProfileInputContainer/ProfileInputContainer.jsx
  src/components/SignUp/ProfileForm.jsx
  src/components/SignUp/SignUpForm.jsx
  src/pages/SignUpPage.jsx
Labels: HTML/CSS

#7 [Common] 네브바 UI 구현
  src/assets/icons/icon-home.svg
  src/assets/icons/icon-message.svg
  src/assets/icons/icon-user.svg
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBarItem.jsx
  src/routes/Router.jsx
Labels: 💄 HTML/CSS

#8 [Profile] 프로필 페이지 UI 구현
  src/components/Profile/MyProfileHeader.jsx
  src/components/Profile/PostContainer.jsx
  src/components/Profile/ProductsContainer.jsx
  src/components/Profile/UserProfileHeader.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: 💄 HTML/CSS

#10 [Follow] FollowerPage, FollowingPage UI 구현
  src/assets/images/basic-profile-m.png
  src/components/Header/FollowHeader.jsx
  src/components/UserItem/UserFollowListItem.jsx
  src/components/UserItem/UserInfo.jsx
  src/components/UserItem/UserSearchListItem.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: 💄 HTML/CSS

#11 [Profile] ProfileEditPage UI구현
  src/pages/ProfileEditPage.jsx
  src/routes/Router.jsx
Labels: 💄 HTML/CSS

#5 [Chat] Chat UI 구현
  src/assets/images/Ellipse-1.png
  src/assets/images/chat-exapmle.png
  src/assets/images/post-img-example.png
  src/components/chat/BottomSheet.jsx
  src/components/chat/ChatItem.jsx
  src/components/chat/ChatList.jsx
  src/components/chat/ChatMessage.jsx
  src/components/chat/ChatRoom.jsx
  src/components/chat/MyChatMessage.jsx
  src/components/chat/ReceiveImage.jsx
  src/components/chat/ReceiveText.jsx
  src/components/chat/SendImage.jsx
  src/components/chat/SendText.jsx
Labels: 💄 HTML/CSS

#6 [Home] 홈 페이지 UI 구현
  src/pages/HomePage.jsx
Labels: 💄 HTML/CSS

#14 [Common] TextInput Placeholder 스타일 추가
  src/components/Input/TextInput.jsx
Labels: 💄 HTML/CSS

#13 [Common] 댓글/채팅 입력창 UI 구현
  src/Globalstyled.jsx
  src/components/Input/TextInputBox.jsx
Labels: 💄 HTML/CSS

#17 [Modal] Alert Modal UI 구현
  src/components/Modal/AlertModal.jsx
Labels: 💄 HTML/CSS

#16 [Post]post UI구현
  src/components/Post/PostReply.jsx
  src/components/Post/PostUpload.jsx
Labels: 💄 HTML/CSS

#18 [Signup] 회원가입 기능 구현
  src/api/baseInstance.js
  src/components/Button/Button.jsx
  src/components/Header/Header.jsx
  src/components/Input/ProfileImageUploader.jsx
  src/components/Input/TextInput.jsx
  src/components/ProfileInputContainer/ProfileInputContainer.jsx
  src/components/SignUp/ProfileForm.jsx
  src/components/SignUp/SignUpForm.jsx
  src/pages/ProfileEditPage.jsx
  src/pages/SignUpPage.jsx
Labels: ✨ 기능 추가

#20 [Pages] Page들 UI 구현
  src/components/Chat/BottomSheet.jsx
  src/components/Chat/ChatItem.jsx
  src/components/Chat/ChatList.jsx
  src/components/Chat/ChatMessage.jsx
  src/components/Chat/ChatRoom.jsx
  src/components/Chat/MyChatMessage.jsx
  src/components/Chat/ReceiveImage.jsx
  src/components/Chat/ReceiveText.jsx
  src/components/Chat/SendImage.jsx
  src/components/Chat/SendText.jsx
  src/components/Header/Header.jsx
  src/components/Input/TextInputBox.jsx
  src/components/Post/PostComment.jsx
  src/components/Post/PostUpload.jsx
  src/components/Product/AddProduct.jsx
  src/components/Product/ImageUpload.jsx
  src/components/Product/ProductUpload.jsx
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/PostPage.jsx
  src/pages/PostUploadPage.jsx
  src/pages/ProductUploadPage.jsx
Labels: 💄 HTML/CSS

#21 [Login] 로그인 기능 구현
  src/App.js
  src/api/instance/authInstance.js
  src/api/instance/baseInstance.js
  src/components/Login/LoginForm.jsx
  src/components/SignUp/ProfileForm.jsx
  src/components/SignUp/SignUpForm.jsx
  src/pages/ProfileEditPage.jsx
  src/pages/SignUpPage.jsx
  src/routes/Router.jsx
  src/states/LoginState.js
Labels: ✨ 기능 추가

#22 [Home/ProfilePage] 코드 스타일, svg 수정 및 컴포넌트명 변경
  src/assets/icons/icon-message.svg
  src/assets/icons/icon-post-album-off.svg
  src/assets/icons/icon-post-album-on.svg
  src/assets/icons/icon-post-album.svg
  src/assets/icons/icon-post-list-off.svg
  src/assets/icons/icon-post-list-on.svg
  src/assets/icons/icon-post-list.svg
  src/components/Profile/MyInfoBtns.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/components/Profile/UserInfoBtns.jsx
  src/components/Profile/UserProfileHeader.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#23 [Common] Header 타입 추가 구현
  src/assets/images/logo.png
  src/components/Header/FollowHeader.jsx
  src/components/Header/Header.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#24 [WelcomePage] WelcomePage UI 구현
  src/assets/icons/email.svg
  src/assets/icons/facebook.svg
  src/assets/icons/google.svg
  src/assets/icons/icon-user-yellow.svg
  src/assets/icons/kakao.svg
  src/assets/images/Logo.png
  src/pages/WelcomePage.jsx
  src/routes/Router.jsx
Labels: 💄 HTML/CSS

#25 [WelcomePage] 로고파일 이름 수정
  src/assets/images/main-logo.png
  src/pages/WelcomePage.jsx
Labels: 💄 HTML/CSS, 📷 ETC

#26 [Common] 공통 BottomSheet UI 구현
  src/components/Chat/BottomSheet.jsx
  src/components/Modal/BottomSheetContent.jsx
  src/components/Modal/BottomSheetModal.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#31 [Feed] 홈 화면 피드 기능 구현
  src/components/Post/PostCard.jsx
  src/pages/HomePage.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS, ♻️ 리팩토링

#32 [Profile] 프로필 정보 & 상품목록 & 팔로우
  src/components/Button/Button.jsx
  src/components/Profile/MyInfoBtns.jsx
  src/components/Profile/ProductItem.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/components/Profile/UserInfoBtns.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: ✨ 기능 추가

#34 [Login] localStorage 오류 수정
  src/components/Login/LoginForm.jsx
Labels: 🐛 버그, ♻️ 리팩토링

#36 [Feed] 홈 피드 게시글 신고 기능
  src/components/Modal/BottomSheetContent.jsx
  src/components/Modal/BottomSheetModal.jsx
  src/components/Modal/ConfirmModal.jsx
  src/components/Post/PostCard.jsx
  src/pages/HomePage.jsx
Labels: ✨ 기능 추가

#37 [Post] Post UI 추가 구현
  src/components/Header/Header.jsx
  src/components/NavBar/NavBar.jsx
  src/components/Post/PostCard.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#38 [Post] 매개변수 이름 변경
  src/components/Post/PostCard.jsx
  src/pages/HomePage.jsx
Labels: ♻️ 리팩토링

#39 [Post] merge 오류 수정
  src/components/Post/PostCard.jsx
Labels: 🐛 버그

#35 [Splash] Splash 화면 구현
  src/App.js
  src/components/Splash/Splash.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#41 [Product] 상품등록 input type변경 & 이미지 업로드 수정
  src/components/Input/RadioInput.jsx
  src/components/Product/ImageUpload.jsx
  src/components/Product/ProductUpload.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#42 [Post Detail] 상세페이지 조건부 모달,바텀시트 신고기능 구현
  src/pages/PostPage.jsx
Labels: ✨ 기능 추가

#45 [Post] 글 수정 페이지 버그 수정
  src/components/Post/PostUpload.jsx
  src/pages/PostEditPage.jsx
  src/pages/PostUploadPage.jsx
Labels: 🐛 버그

#43 [follow] 팔로잉 팔로워 페이지 기능 구현
  src/components/Profile/MyInfoBtns.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/UserItem/UserFollowListItem.jsx
  src/components/UserItem/UserInfo.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: ✨ 기능 추가

#44 [Post Detail] 모달, 수정 삭제 기능 구현
  src/pages/PostPage.jsx
Labels: ✨ 기능 추가

#40 [Profile] 바텀시트 적용 & 프로필 페이지 피드 기능 구현
  src/api/instance/authInstance.js
  src/assets/icons/icon-multiple.svg
  src/components/Modal/BottomSheetModal.jsx
  src/components/Profile/PostGalleryItem.jsx
  src/components/Profile/ProductItem.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: ✨ 기능 추가

#46 🐛 : 오타수정
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
Labels: ♻️ 리팩토링

#47 [Profile] git 꼬임 해결
  src/components/Profile/ProfileInfo.jsx
Labels: 🐛 버그

#48 [Post Comments]댓글 기능 구현
  src/components/Input/TextInputBox.jsx
  src/components/Post/PostComment.jsx
  src/pages/PostPage.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#49 [product] 상품 상세 모달 및 삭제, 수정 기능 구현
  src/Globalstyled.jsx
  src/components/Input/RadioInput.jsx
  src/components/Input/TextInput.jsx
  src/components/Product/ImageUpload.jsx
  src/components/Product/ProductCard.jsx
  src/components/Product/ProductUpload.jsx
  src/components/Profile/ProductItem.jsx
  src/components/Profile/ProfileProducts.jsx
  src/pages/HomePage.jsx
  src/pages/ProductEditPage.jsx
  src/pages/ProductUploadPage.jsx
  src/routes/Router.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS, ♻️ 리팩토링

#51 [Profile] Profile 전체적 수정 및 Validation
  src/components/Profile/PostGalleryItem.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/components/Profile/UserInfoBtns.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: ♻️ 리팩토링

#50 [Post Comments]수정,삭제 기능 구현
  src/components/Post/PostComment.jsx
  src/pages/PostPage.jsx
Labels: ✨ 기능 추가

#52 [Home] 스크롤 위치 및 디자인 수정
  src/pages/HomePage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#53 [NavBar/Header] NavBar 아이콘 색상 버그 고침
  src/components/Header/Header.jsx
  src/components/Input/SearchInput.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBarItem.jsx
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/PostPage.jsx
  src/pages/UserProfilePage.jsx
  src/pages/WelcomePage.jsx
  src/states/PathState.js
Labels: 🐛 버그, ♻️ 리팩토링

#54 [Profile] 프로필 페이지 수정 및 follow 0명 처리
  src/components/Profile/ProductItem.jsx
  src/components/Profile/ProfileInfo.jsx
  src/components/Profile/ProfilePosts.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#55 [Merge] merge conflict 잘못 병합된 것 해결
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: 📷 ETC

#56 💄 Design: Page Header UI 수정
  src/pages/ChatListPage.jsx
  src/pages/ChatRoomPage.jsx
  src/pages/MyProfilePage.jsx
Labels: 💄 HTML/CSS

#57 [Common] useModal 커스텀훅 구현
  src/components/Post/PostComment.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/hooks/useModal.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/PostPage.jsx
Labels: ✨ 기능 추가, ♻️ 리팩토링

#58 [Chat] chat 기능구현
  src/components/Chat/ChatItem.jsx
  src/components/Chat/ChatList.jsx
  src/components/Chat/ChatRoom.jsx
  src/pages/ChatRoomPage.jsx
Labels: ✨ 기능 추가, 💄 HTML/CSS

#59 [Common] Not found 페이지 UI 구현
  src/assets/images/not-found.png
  src/components/Profile/ProfilePosts.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
  src/pages/NotFoundPage.jsx
Labels: 💄 HTML/CSS

#60 [Feed] 스크롤 위로 가기 기능 수정
  src/components/Header/Header.jsx
  src/pages/HomePage.jsx
Labels: ♻️ 리팩토링

#61 [Post Comments]댓글 엔터처리,프로필 이동
  public/index.html
  src/components/Input/TextInputBox.jsx
  src/components/Post/PostComment.jsx
Labels: ✨ 기능 추가

#62 [Post] PostCard Design 디자인 수정 및 코드 리팩토링
  src/components/Post/PostCard.jsx
  src/components/Profile/ProfilePosts.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#63 [Post] postcard 작성 시간 변환
  src/components/Post/PostCard.jsx
  src/components/Post/PostComment.jsx
  src/utils/convertTime.js
Labels: ♻️ 리팩토링

#65 [Validation] 접근성 고려, 콘솔정리
  src/Globalstyled.jsx
  src/components/Chat/ChatList.jsx
  src/components/Chat/ChatRoom.jsx
  src/components/Input/RadioInput.jsx
  src/components/Input/TextInputBox.jsx
  src/pages/ProductEditPage.jsx
  src/pages/ProductUploadPage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#64 [Validation] 마크업 validation 및 접근성 고려
  src/components/Input/ProfileImageUploader.jsx
  src/components/Post/PostCard.jsx
  src/components/Post/PostUpload.jsx
  src/components/UserItem/UserInfo.jsx
  src/pages/HomePage.jsx
  src/pages/PostPage.jsx
  src/routes/Router.jsx
  src/states/PathState.js
Labels: 💄 HTML/CSS, ♻️ 리팩토링

#67 [Common] 로딩 스피너 적용
  src/components/Loading/Loading.jsx
  src/components/Profile/ProfilePosts.jsx
  src/components/Profile/ProfileProducts.jsx
  src/pages/FollowersPage.jsx
  src/pages/FollowingsPage.jsx
  src/pages/HomePage.jsx
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: ✨ 기능 추가

#69 [Page] 스크롤 오류 수정
  src/Globalstyled.jsx
Labels: ♻️ 리팩토링

#70 [Common] navbar 오류 수정
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBarItem.jsx
Labels: ♻️ 리팩토링

#71 [Welcome] WelcomePage UI 수정 및 파비콘 추가
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/pages/WelcomePage.jsx
Labels: 💄 HTML/CSS, ♻️ 리팩토링, 📷 ETC

#72 [Common] 불필요한 파일 삭제 및 manifest 에러 해결
  public/index.html
  src/App.test.js
  src/assets/icons/icon-home-fill.svg
  src/assets/icons/icon-message-fill.svg
  src/assets/icons/icon-user-fill.svg
  src/assets/images/Ellipse-1.png
  src/assets/images/img-button.png
  src/setupTests.js
Labels: 🐛 버그, 📷 ETC

#73 [Common] bottomSheet 애니메이션 추가
  src/components/Modal/BottomSheetModal.jsx
Labels: 💄 HTML/CSS

#74 [Post Comments]댓글기능 수정
  src/utils/convertTime.js
Labels: ♻️ 리팩토링

#75 [Common] NavBar 오류수정
  src/assets/icons/icon-message.svg
  src/components/NavBar/NavBar.jsx
Labels: 🐛 버그, 📷 ETC

#76 [Profile] 반응형 시 너비 변경
  src/pages/MyProfilePage.jsx
  src/pages/UserProfilePage.jsx
Labels: 💄 HTML/CSS
